set_property SRC_FILE_INFO {cfile:/home/prateek/vivado/led_vcu/led_vcu.srcs/constrs_1/new/led_constraint.xdc rfile:../../../led_vcu.srcs/constrs_1/new/led_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY24 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT32 [get_ports led]
